#!/usr/bin/env bash
#script that displays lines containing the bash word, thus allowing you to easily get the PID of your Bash process.
# shellcheck disable=SC2009
#grep searches for "bash" and returns the the processes
ps -aufx | grep bash
