#!/usr/bin/env bash
#script displays the content of the file /etc/passwd, using the while loop + IFS.
# Set the input file
input_file="/etc/passwd"

# Read the file line by line using a while loop
while IFS=: read -r username _ uid gid info home shell; do
    # Display the required information based on the structure provided
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $_, more info about the user here: $info"
done < "$input_file"
