#!/usr/bin/env bash
#This script displays numbers from 1 to 20 and also echos differernt strings
count=1
while [ $count -le 20 ]
do

	echo "$count"
	((count++))
	case $count in
		4)
			echo -e "$count\nbad luck from China"
			((count++))
		;;
		9)
			echo -e "$count\nbad luck from Japan"
			((count++))
		;;
		17)
			echo -e "$count\nbad luck from Italy"
			((count++))
		;;

		*)
	esac


done
